version: "3.0"
services:
  back-end:
    build: ./spaceExplorer/
    container_name: space-explorer
    ports:
      - "8080:8080"
    env_file:
      - '.env'
    depends_on:
      - database
      
  database:
    image: postgres:14-alpine
    container_name: space-explorer-db
    ports:
      - "5432:5432"
    env_file:
      - '.env'

volumes:
  volumes:
